### PR TITLE
Add bower integration.

### PR DESCRIPTION
**Pull request by bronzehedwick**
We use hoverintent with bower at work, and would like tighter integration.

### CODE REVIEW

**Comment by bronzehedwick** [comment]
Thanks! I think you as the package owner would have to run `bower register` as per the instructions to all installation via shortname (e.g. `bower install hoverintent`) http://bower.io/docs/creating-packages/#register

**Comment by tristen** [comment]
@bronzehedwick Added you as a collaborator!

**Comment by bronzehedwick** [comment]
:) thanks! I'll register the project!

**Comment by bronzehedwick** [comment]
Created a new `v0.2.3` tag, as bower needs tags or master branch to work. The hoverintent namespace was already taken, so I published as hoverintentjs. Thanks for all the great work!

**Comment by tristen** [comment]
:+1: :+1:

**Pull request merged**
